apiVersion: secret.example.com/v1alpha1
kind: Password
metadata:
  labels:
    app.kubernetes.io/name: password
    app.kubernetes.io/instance: password-sample
    app.kubernetes.io/part-of: projects
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: projects
  name: password-sample
spec:
  # TODO(user): Add fields here
